---
- name: dect-ansible
  hosts: localhost
  become: yes
  user: root

  tasks:

  - name: upgrade
    apt: upgrade=dist force_apt_get=yes

  #- name: configure ip

  - name: install dnsmasq
    apt:
      name: dnsmasq
      state: present 

  - name: configure dnsmasq
    copy:
      src: /home/pi/dect/dnsmasq.conf
      dest: /etc/dnsmasq.conf

  - name: start dnsmasq service
    systemd:
      name: dnsmasq
      daemon_reload: yes
      state: restarted
      enabled: yes
